import { Book } from '@book-store/shared-models';

export const BOOKS_DATA: Book[] = [
  {
    Id: '8ef9f86b-cdc4-49ab-88de-f641e8d0ab73',
    Author: 'Chinua Achebe',
    Country: 'Nigeria',
    ImageLink: 'assets/images/things-fall-apart.jpg',
    Language: 'English',
    Link: 'https://en.wikipedia.org/wiki/Things_Fall_Apart\n',
    Pages: 209,
    Title: 'Things Fall Apart',
    Year: 1958,
    Price: 243,
  },
  {
    Id: 'ab38cb7b-f4de-4c3f-9463-dcba1bd62f36',
    Author: 'Hans Christian Andersen',
    Country: 'Denmark',
    ImageLink: 'assets/images/fairy-tales.jpg',
    Language: 'Danish',
    Link: 'https://en.wikipedia.org/wiki/Fairy_Tales_Told_for_Children._First_Collection.\n',
    Pages: 784,
    Title: 'Fairy tales',
    Year: 1836,
    Price: 101,
  },
  {
    Id: '591806aa-ea46-4f10-a971-dbae6dbf5e5d',
    Author: 'Dante Alighieri',
    Country: 'Italy',
    ImageLink: 'assets/images/the-divine-comedy.jpg',
    Language: 'Italian',
    Link: 'https://en.wikipedia.org/wiki/Divine_Comedy\n',
    Pages: 928,
    Title: 'The Divine Comedy',
    Year: 1315,
    Price: 149,
  },
  {
    Id: 'b8d1409d-fd55-42b9-9df4-9428d9e2edfc',
    Author: 'Unknown',
    Country: 'Sumer and Akkadian Empire',
    ImageLink: 'assets/images/the-epic-of-gilgamesh.jpg',
    Language: 'Akkadian',
    Link: 'https://en.wikipedia.org/wiki/Epic_of_Gilgamesh\n',
    Pages: 160,
    Title: 'The Epic Of Gilgamesh',
    Year: -1700,
    Price: 259,
  },
  {
    Id: 'a8e5ecb2-8ccd-4710-8883-252110d9f669',
    Author: 'Unknown',
    Country: 'Achaemenid Empire',
    ImageLink: 'assets/images/the-book-of-job.jpg',
    Language: 'Hebrew',
    Link: 'https://en.wikipedia.org/wiki/Book_of_Job\n',
    Pages: 176,
    Title: 'The Book Of Job',
    Year: -600,
    Price: 270,
  },
  {
    Id: '7be2df3a-ce55-4a1d-b2b3-cfcf79ce8627',
    Author: 'Unknown',
    Country: 'India/Iran/Iraq/Egypt/Tajikistan',
    ImageLink: 'assets/images/one-thousand-and-one-nights.jpg',
    Language: 'Arabic',
    Link: 'https://en.wikipedia.org/wiki/One_Thousand_and_One_Nights\n',
    Pages: 288,
    Title: 'One Thousand and One Nights',
    Year: 1200,
    Price: 125,
  },
  {
    Id: 'b9905116-ea11-41a7-9b5e-4ef116bd7247',
    Author: 'Unknown',
    Country: 'Iceland',
    ImageLink: 'assets/images/njals-saga.jpg',
    Language: 'Old Norse',
    Link: 'https://en.wikipedia.org/wiki/Nj%C3%A1ls_saga\n',
    Pages: 384,
    Title: 'Nj\u00E1l\u0027s Saga',
    Year: 1350,
    Price: 114,
  },
  {
    Id: '681f8f0d-4b9b-4296-92f8-fba4d7564077',
    Author: 'Jane Austen',
    Country: 'United Kingdom',
    ImageLink: 'assets/images/pride-and-prejudice.jpg',
    Language: 'English',
    Link: 'https://en.wikipedia.org/wiki/Pride_and_Prejudice\n',
    Pages: 226,
    Title: 'Pride and Prejudice',
    Year: 1813,
    Price: 156,
  },
  {
    Id: '310d34e6-d394-4529-a0b1-8d80b6c3ac5c',
    Author: 'Honor\u00E9 de Balzac',
    Country: 'France',
    ImageLink: 'assets/images/le-pere-goriot.jpg',
    Language: 'French',
    Link: 'https://en.wikipedia.org/wiki/Le_P%C3%A8re_Goriot\n',
    Pages: 443,
    Title: 'Le P\u00E8re Goriot',
    Year: 1835,
    Price: 206,
  },
  {
    Id: '928104ef-270e-4463-8de1-64f5906e707a',
    Author: 'Samuel Beckett',
    Country: 'Republic of Ireland',
    ImageLink: 'assets/images/molloy-malone-dies-the-unnamable.jpg',
    Language: 'French, English',
    Link: 'https://en.wikipedia.org/wiki/Molloy_(novel)\n',
    Pages: 256,
    Title: 'Molloy, Malone Dies, The Unnamable, the trilogy',
    Year: 1952,
    Price: 168,
  },
  {
    Id: '2936324f-06b1-494d-a97c-51117a292a1e',
    Author: 'Giovanni Boccaccio',
    Country: 'Italy',
    ImageLink: 'assets/images/the-decameron.jpg',
    Language: 'Italian',
    Link: 'https://en.wikipedia.org/wiki/The_Decameron\n',
    Pages: 1024,
    Title: 'The Decameron',
    Year: 1351,
    Price: 219,
  },
  {
    Id: 'fc272bc8-6ee9-4a23-ab70-4c3d0b3d6683',
    Author: 'Jorge Luis Borges',
    Country: 'Argentina',
    ImageLink: 'assets/images/ficciones.jpg',
    Language: 'Spanish',
    Link: 'https://en.wikipedia.org/wiki/Ficciones\n',
    Pages: 224,
    Title: 'Ficciones',
    Year: 1965,
    Price: 184,
  },
  {
    Id: '170ce6a8-61be-4329-8093-19f5fbf364ee',
    Author: 'Emily Bront\u00EB',
    Country: 'United Kingdom',
    ImageLink: 'assets/images/wuthering-heights.jpg',
    Language: 'English',
    Link: 'https://en.wikipedia.org/wiki/Wuthering_Heights\n',
    Pages: 342,
    Title: 'Wuthering Heights',
    Year: 1847,
    Price: 113,
  },
  {
    Id: 'b861e8d6-23f2-4a1a-b9c5-fa535ff9c299',
    Author: 'Albert Camus',
    Country: 'Algeria, French Empire',
    ImageLink: 'assets/images/l-etranger.jpg',
    Language: 'French',
    Link: 'https://en.wikipedia.org/wiki/The_Stranger_(novel)\n',
    Pages: 185,
    Title: 'The Stranger',
    Year: 1942,
    Price: 221,
  },
  {
    Id: 'b0314922-f15f-4b40-9b5d-03b00d383fbc',
    Author: 'Paul Celan',
    Country: 'Romania, France',
    ImageLink: 'assets/images/poems-paul-celan.jpg',
    Language: 'German',
    Link: '\n',
    Pages: 320,
    Title: 'Poems',
    Year: 1952,
    Price: 287,
  },
  {
    Id: '52d07b0e-1e4d-40f6-9060-af0406348696',
    Author: 'Louis-Ferdinand C\u00E9line',
    Country: 'France',
    ImageLink: 'assets/images/voyage-au-bout-de-la-nuit.jpg',
    Language: 'French',
    Link: 'https://en.wikipedia.org/wiki/Journey_to_the_End_of_the_Night\n',
    Pages: 505,
    Title: 'Journey to the End of the Night',
    Year: 1932,
    Price: 164,
  },
  {
    Id: 'edc7ae66-3cae-4f9d-adc6-4b938bb21b34',
    Author: 'Miguel de Cervantes',
    Country: 'Spain',
    ImageLink: 'assets/images/don-quijote-de-la-mancha.jpg',
    Language: 'Spanish',
    Link: 'https://en.wikipedia.org/wiki/Don_Quixote\n',
    Pages: 1056,
    Title: 'Don Quijote De La Mancha',
    Year: 1610,
    Price: 217,
  },
  {
    Id: 'ff127869-b436-463e-b9b0-3ab7cd4506a4',
    Author: 'Geoffrey Chaucer',
    Country: 'England',
    ImageLink: 'assets/images/the-canterbury-tales.jpg',
    Language: 'English',
    Link: 'https://en.wikipedia.org/wiki/The_Canterbury_Tales\n',
    Pages: 544,
    Title: 'The Canterbury Tales',
    Year: 1450,
    Price: 129,
  },
  {
    Id: '5f6cfe46-5c34-4401-a555-adc10a2cb93b',
    Author: 'Anton Chekhov',
    Country: 'Russia',
    ImageLink: 'assets/images/stories-of-anton-chekhov.jpg',
    Language: 'Russian',
    Link: 'https://en.wikipedia.org/wiki/List_of_short_stories_by_Anton_Chekhov\n',
    Pages: 194,
    Title: 'Stories',
    Year: 1886,
    Price: 262,
  },
  {
    Id: 'c21b44d5-ff1f-4477-a0b1-1080b755b22f',
    Author: 'Joseph Conrad',
    Country: 'United Kingdom',
    ImageLink: 'assets/images/nostromo.jpg',
    Language: 'English',
    Link: 'https://en.wikipedia.org/wiki/Nostromo\n',
    Pages: 320,
    Title: 'Nostromo',
    Year: 1904,
    Price: 112,
  },
  {
    Id: 'faad5354-d7f0-4578-8ba3-4dae32a47816',
    Author: 'Charles Dickens',
    Country: 'United Kingdom',
    ImageLink: 'assets/images/great-expectations.jpg',
    Language: 'English',
    Link: 'https://en.wikipedia.org/wiki/Great_Expectations\n',
    Pages: 194,
    Title: 'Great Expectations',
    Year: 1861,
    Price: 286,
  },
  {
    Id: '71e90c6d-c466-4141-9ee9-b82e616c4b9f',
    Author: 'Denis Diderot',
    Country: 'France',
    ImageLink: 'assets/images/jacques-the-fatalist.jpg',
    Language: 'French',
    Link: 'https://en.wikipedia.org/wiki/Jacques_the_Fatalist\n',
    Pages: 596,
    Title: 'Jacques the Fatalist',
    Year: 1796,
    Price: 158,
  },
  {
    Id: 'd3e3c47c-4269-4a05-84ec-022affef3110',
    Author: 'Alfred D\u00F6blin',
    Country: 'Germany',
    ImageLink: 'assets/images/berlin-alexanderplatz.jpg',
    Language: 'German',
    Link: 'https://en.wikipedia.org/wiki/Berlin_Alexanderplatz\n',
    Pages: 600,
    Title: 'Berlin Alexanderplatz',
    Year: 1929,
    Price: 234,
  },
  {
    Id: 'a47865cd-c04f-4707-9a85-d9e67efb9fbc',
    Author: 'Fyodor Dostoevsky',
    Country: 'Russia',
    ImageLink: 'assets/images/crime-and-punishment.jpg',
    Language: 'Russian',
    Link: 'https://en.wikipedia.org/wiki/Crime_and_Punishment\n',
    Pages: 551,
    Title: 'Crime and Punishment',
    Year: 1866,
    Price: 163,
  },
  {
    Id: '20d5998d-91c2-4440-85b3-dff01d861b22',
    Author: 'Fyodor Dostoevsky',
    Country: 'Russia',
    ImageLink: 'assets/images/the-idiot.jpg',
    Language: 'Russian',
    Link: 'https://en.wikipedia.org/wiki/The_Idiot\n',
    Pages: 656,
    Title: 'The Idiot',
    Year: 1869,
    Price: 218,
  },
  {
    Id: '7049426d-fcc1-4c8c-ba44-1c8a96e7306b',
    Author: 'Fyodor Dostoevsky',
    Country: 'Russia',
    ImageLink: 'assets/images/the-possessed.jpg',
    Language: 'Russian',
    Link: 'https://en.wikipedia.org/wiki/Demons_(Dostoyevsky_novel)\n',
    Pages: 768,
    Title: 'The Possessed',
    Year: 1872,
    Price: 194,
  },
  {
    Id: '775ff4d7-53c6-4f87-a2af-8f141698b628',
    Author: 'Fyodor Dostoevsky',
    Country: 'Russia',
    ImageLink: 'assets/images/the-brothers-karamazov.jpg',
    Language: 'Russian',
    Link: 'https://en.wikipedia.org/wiki/The_Brothers_Karamazov\n',
    Pages: 824,
    Title: 'The Brothers Karamazov',
    Year: 1880,
    Price: 191,
  },
  {
    Id: 'cb6f71fe-486f-467a-bdb0-f425a1970af0',
    Author: 'George Eliot',
    Country: 'United Kingdom',
    ImageLink: 'assets/images/middlemarch.jpg',
    Language: 'English',
    Link: 'https://en.wikipedia.org/wiki/Middlemarch\n',
    Pages: 800,
    Title: 'Middlemarch',
    Year: 1871,
    Price: 169,
  },
  {
    Id: '8222f5d1-8287-440d-aa3b-19bdaaf70803',
    Author: 'Ralph Ellison',
    Country: 'United States',
    ImageLink: 'assets/images/invisible-man.jpg',
    Language: 'English',
    Link: 'https://en.wikipedia.org/wiki/Invisible_Man\n',
    Pages: 581,
    Title: 'Invisible Man',
    Year: 1952,
    Price: 209,
  },
  {
    Id: 'b2aef4f8-0107-4f57-9c10-870db310aa74',
    Author: 'Euripides',
    Country: 'Greece',
    ImageLink: 'assets/images/medea.jpg',
    Language: 'Greek',
    Link: 'https://en.wikipedia.org/wiki/Medea_(play)\n',
    Pages: 104,
    Title: 'Medea',
    Year: -431,
    Price: 225,
  },
  {
    Id: '36bf6f0f-a0fb-4cd2-b4fb-b132a5f129a8',
    Author: 'William Faulkner',
    Country: 'United States',
    ImageLink: 'assets/images/absalom-absalom.jpg',
    Language: 'English',
    Link: 'https://en.wikipedia.org/wiki/Absalom,_Absalom!\n',
    Pages: 313,
    Title: 'Absalom, Absalom!',
    Year: 1936,
    Price: 258,
  },
  {
    Id: 'c775ee13-0c87-4bdb-a792-7a10a65b0475',
    Author: 'William Faulkner',
    Country: 'United States',
    ImageLink: 'assets/images/the-sound-and-the-fury.jpg',
    Language: 'English',
    Link: 'https://en.wikipedia.org/wiki/The_Sound_and_the_Fury\n',
    Pages: 326,
    Title: 'The Sound and the Fury',
    Year: 1929,
    Price: 154,
  },
  {
    Id: 'b19f093b-6be2-4f30-ab32-37bfff22e135',
    Author: 'Gustave Flaubert',
    Country: 'France',
    ImageLink: 'assets/images/madame-bovary.jpg',
    Language: 'French',
    Link: 'https://en.wikipedia.org/wiki/Madame_Bovary\n',
    Pages: 528,
    Title: 'Madame Bovary',
    Year: 1857,
    Price: 270,
  },
  {
    Id: 'b108ac07-6d3a-446a-9097-e65d7897dfcb',
    Author: 'Gustave Flaubert',
    Country: 'France',
    ImageLink: 'assets/images/l-education-sentimentale.jpg',
    Language: 'French',
    Link: 'https://en.wikipedia.org/wiki/Sentimental_Education\n',
    Pages: 606,
    Title: 'Sentimental Education',
    Year: 1869,
    Price: 232,
  },
  {
    Id: '71bf7898-d951-41bf-871d-83a4b6d08d99',
    Author: 'Federico Garc\u00EDa Lorca',
    Country: 'Spain',
    ImageLink: 'assets/images/gypsy-ballads.jpg',
    Language: 'Spanish',
    Link: 'https://en.wikipedia.org/wiki/Gypsy_Ballads\n',
    Pages: 218,
    Title: 'Gypsy Ballads',
    Year: 1928,
    Price: 151,
  },
  {
    Id: '1044d89c-c86a-466e-8c19-3d5a1c887eeb',
    Author: 'Gabriel Garc\u00EDa M\u00E1rquez',
    Country: 'Colombia',
    ImageLink: 'assets/images/one-hundred-years-of-solitude.jpg',
    Language: 'Spanish',
    Link: 'https://en.wikipedia.org/wiki/One_Hundred_Years_of_Solitude\n',
    Pages: 417,
    Title: 'One Hundred Years of Solitude',
    Year: 1967,
    Price: 245,
  },
  {
    Id: 'e482bdff-1180-4768-99cb-b99dc4dbbd4a',
    Author: 'Gabriel Garc\u00EDa M\u00E1rquez',
    Country: 'Colombia',
    ImageLink: 'assets/images/love-in-the-time-of-cholera.jpg',
    Language: 'Spanish',
    Link: 'https://en.wikipedia.org/wiki/Love_in_the_Time_of_Cholera\n',
    Pages: 368,
    Title: 'Love in the Time of Cholera',
    Year: 1985,
    Price: 171,
  },
  {
    Id: 'a6161993-e2a8-4aba-81ab-dbd704ca0466',
    Author: 'Johann Wolfgang von Goethe',
    Country: 'Saxe-Weimar',
    ImageLink: 'assets/images/faust.jpg',
    Language: 'German',
    Link: 'https://en.wikipedia.org/wiki/Goethe%27s_Faust\n',
    Pages: 158,
    Title: 'Faust',
    Year: 1832,
    Price: 189,
  },
  {
    Id: '2fd05a90-a8d0-4d67-a008-31c4d87bf807',
    Author: 'Nikolai Gogol',
    Country: 'Russia',
    ImageLink: 'assets/images/dead-souls.jpg',
    Language: 'Russian',
    Link: 'https://en.wikipedia.org/wiki/Dead_Souls\n',
    Pages: 432,
    Title: 'Dead Souls',
    Year: 1842,
    Price: 205,
  },
  {
    Id: 'f233df57-15a2-4f5d-95bf-ef41635719a6',
    Author: 'G\u00FCnter Grass',
    Country: 'Germany',
    ImageLink: 'assets/images/the-tin-drum.jpg',
    Language: 'German',
    Link: 'https://en.wikipedia.org/wiki/The_Tin_Drum\n',
    Pages: 600,
    Title: 'The Tin Drum',
    Year: 1959,
    Price: 282,
  },
  {
    Id: '968f68e0-52b2-4bb5-a352-37f93f57c7ba',
    Author: 'Jo\u00E3o Guimar\u00E3es Rosa',
    Country: 'Brazil',
    ImageLink: 'assets/images/the-devil-to-pay-in-the-backlands.jpg',
    Language: 'Portuguese',
    Link: 'https://en.wikipedia.org/wiki/The_Devil_to_Pay_in_the_Backlands\n',
    Pages: 494,
    Title: 'The Devil to Pay in the Backlands',
    Year: 1956,
    Price: 283,
  },
  {
    Id: '581f9b40-633e-447e-b9b4-8311d7e1ec50',
    Author: 'Knut Hamsun',
    Country: 'Norway',
    ImageLink: 'assets/images/hunger.jpg',
    Language: 'Norwegian',
    Link: 'https://en.wikipedia.org/wiki/Hunger_(Hamsun_novel)\n',
    Pages: 176,
    Title: 'Hunger',
    Year: 1890,
    Price: 144,
  },
  {
    Id: '56afbd79-93c2-4dc3-b1aa-578494753b9b',
    Author: 'Ernest Hemingway',
    Country: 'United States',
    ImageLink: 'assets/images/the-old-man-and-the-sea.jpg',
    Language: 'English',
    Link: 'https://en.wikipedia.org/wiki/The_Old_Man_and_the_Sea\n',
    Pages: 128,
    Title: 'The Old Man and the Sea',
    Year: 1952,
    Price: 182,
  },
  {
    Id: '0e3e598c-eda9-4ab1-8807-fc5b05ad61fa',
    Author: 'Homer',
    Country: 'Greece',
    ImageLink: 'assets/images/the-iliad-of-homer.jpg',
    Language: 'Greek',
    Link: 'https://en.wikipedia.org/wiki/Iliad\n',
    Pages: 608,
    Title: 'Iliad',
    Year: -735,
    Price: 263,
  },
  {
    Id: 'ff31fd4e-c181-4016-b38b-4af00a56a8d0',
    Author: 'Homer',
    Country: 'Greece',
    ImageLink: 'assets/images/the-odyssey-of-homer.jpg',
    Language: 'Greek',
    Link: 'https://en.wikipedia.org/wiki/Odyssey\n',
    Pages: 374,
    Title: 'Odyssey',
    Year: -800,
    Price: 155,
  },
  {
    Id: '01fb0bf2-004a-4ce1-b867-1abcb724b7bb',
    Author: 'Henrik Ibsen',
    Country: 'Norway',
    ImageLink: 'assets/images/a-Dolls-house.jpg',
    Language: 'Norwegian',
    Link: 'https://en.wikipedia.org/wiki/A_Doll%27s_House\n',
    Pages: 68,
    Title: 'A Doll\u0027s House',
    Year: 1879,
    Price: 285,
  },
  {
    Id: '12ab652c-d49a-42bb-bd44-45fab17a3635',
    Author: 'James Joyce',
    Country: 'Irish Free State',
    ImageLink: 'assets/images/ulysses.jpg',
    Language: 'English',
    Link: 'https://en.wikipedia.org/wiki/Ulysses_(novel)\n',
    Pages: 228,
    Title: 'Ulysses',
    Year: 1922,
    Price: 103,
  },
  {
    Id: 'b38d85da-82db-418b-9e73-9c6aaee76a8c',
    Author: 'Franz Kafka',
    Country: 'Czechoslovakia',
    ImageLink: 'assets/images/stories-of-franz-kafka.jpg',
    Language: 'German',
    Link: 'https://en.wikipedia.org/wiki/Franz_Kafka_bibliography#Short_stories\n',
    Pages: 488,
    Title: 'Stories',
    Year: 1924,
    Price: 288,
  },
  {
    Id: '00f44751-dcc1-4557-aaf0-29d7d3c458a0',
    Author: 'Franz Kafka',
    Country: 'Czechoslovakia',
    ImageLink: 'assets/images/the-trial.jpg',
    Language: 'German',
    Link: 'https://en.wikipedia.org/wiki/The_Trial\n',
    Pages: 160,
    Title: 'The Trial',
    Year: 1925,
    Price: 218,
  },
  {
    Id: '7e23bbb9-5f48-47f9-9d72-de2fe0a55609',
    Author: 'Franz Kafka',
    Country: 'Czechoslovakia',
    ImageLink: 'assets/images/the-castle.jpg',
    Language: 'German',
    Link: 'https://en.wikipedia.org/wiki/The_Castle_(novel)\n',
    Pages: 352,
    Title: 'The Castle',
    Year: 1926,
    Price: 147,
  },
  {
    Id: '6d77f60f-3c3a-4380-9c21-46e7c7c0a739',
    Author: 'K\u0101lid\u0101sa',
    Country: 'India',
    ImageLink: 'assets/images/the-recognition-of-shakuntala.jpg',
    Language: 'Sanskrit',
    Link: 'https://en.wikipedia.org/wiki/Abhij%C3%B1%C4%81na%C5%9B%C4%81kuntalam\n',
    Pages: 147,
    Title: 'The recognition of Shakuntala',
    Year: 150,
    Price: 260,
  },
  {
    Id: '31403a23-c9dd-49bc-b1b5-4d1df77536ec',
    Author: 'Yasunari Kawabata',
    Country: 'Japan',
    ImageLink: 'assets/images/the-sound-of-the-mountain.jpg',
    Language: 'Japanese',
    Link: 'https://en.wikipedia.org/wiki/The_Sound_of_the_Mountain\n',
    Pages: 288,
    Title: 'The Sound of the Mountain',
    Year: 1954,
    Price: 208,
  },
  {
    Id: '49870be0-ae8d-4ec0-9726-4ebf6d9119ff',
    Author: 'Nikos Kazantzakis',
    Country: 'Greece',
    ImageLink: 'assets/images/zorba-the-greek.jpg',
    Language: 'Greek',
    Link: 'https://en.wikipedia.org/wiki/Zorba_the_Greek\n',
    Pages: 368,
    Title: 'Zorba the Greek',
    Year: 1946,
    Price: 160,
  },
  {
    Id: '1c214ac6-6b0e-45ae-af75-86c2a259492a',
    Author: 'D. H. Lawrence',
    Country: 'United Kingdom',
    ImageLink: 'assets/images/sons-and-lovers.jpg',
    Language: 'English',
    Link: 'https://en.wikipedia.org/wiki/Sons_and_Lovers\n',
    Pages: 432,
    Title: 'Sons and Lovers',
    Year: 1913,
    Price: 265,
  },
  {
    Id: '776ba9be-afd2-4066-8d37-3177124cdd17',
    Author: 'Halld\u00F3r Laxness',
    Country: 'Iceland',
    ImageLink: 'assets/images/independent-people.jpg',
    Language: 'Icelandic',
    Link: 'https://en.wikipedia.org/wiki/Independent_People\n',
    Pages: 470,
    Title: 'Independent People',
    Year: 1934,
    Price: 190,
  },
  {
    Id: 'b5872569-c08a-4062-bc64-e1184fd78e58',
    Author: 'Giacomo Leopardi',
    Country: 'Italy',
    ImageLink: 'assets/images/poems-giacomo-leopardi.jpg',
    Language: 'Italian',
    Link: '\n',
    Pages: 184,
    Title: 'Poems',
    Year: 1818,
    Price: 230,
  },
  {
    Id: '4bddcfc3-7c2e-465a-8ad9-bb81236f672f',
    Author: 'Doris Lessing',
    Country: 'United Kingdom',
    ImageLink: 'assets/images/the-golden-notebook.jpg',
    Language: 'English',
    Link: 'https://en.wikipedia.org/wiki/The_Golden_Notebook\n',
    Pages: 688,
    Title: 'The Golden Notebook',
    Year: 1962,
    Price: 288,
  },
  {
    Id: 'ab8e1ef7-28ad-48ec-8550-2c34024c7032',
    Author: 'Astrid Lindgren',
    Country: 'Sweden',
    ImageLink: 'assets/images/pippi-longstocking.jpg',
    Language: 'Swedish',
    Link: 'https://en.wikipedia.org/wiki/Pippi_Longstocking\n',
    Pages: 160,
    Title: 'Pippi Longstocking',
    Year: 1945,
    Price: 116,
  },
  {
    Id: 'd2c52fc4-953a-4d54-854e-f337b224d678',
    Author: 'Lu Xun',
    Country: 'China',
    ImageLink: 'assets/images/diary-of-a-madman.jpg',
    Language: 'Chinese',
    Link: 'https://en.wikipedia.org/wiki/A_Madman%27s_Diary\n',
    Pages: 389,
    Title: 'Diary of a Madman',
    Year: 1918,
    Price: 212,
  },
  {
    Id: 'ef1ff262-924d-415c-8709-c0c6be9d4c17',
    Author: 'Naguib Mahfouz',
    Country: 'Egypt',
    ImageLink: 'assets/images/children-of-gebelawi.jpg',
    Language: 'Arabic',
    Link: 'https://en.wikipedia.org/wiki/Children_of_Gebelawi\n',
    Pages: 355,
    Title: 'Children of Gebelawi',
    Year: 1959,
    Price: 159,
  },
  {
    Id: '9689d826-ada6-46d9-adf6-6d05fe3d0c7c',
    Author: 'Thomas Mann',
    Country: 'Germany',
    ImageLink: 'assets/images/buddenbrooks.jpg',
    Language: 'German',
    Link: 'https://en.wikipedia.org/wiki/Buddenbrooks\n',
    Pages: 736,
    Title: 'Buddenbrooks',
    Year: 1901,
    Price: 282,
  },
  {
    Id: 'adfdc815-9561-4a60-a009-82ca89abc4c1',
    Author: 'Thomas Mann',
    Country: 'Germany',
    ImageLink: 'assets/images/the-magic-mountain.jpg',
    Language: 'German',
    Link: 'https://en.wikipedia.org/wiki/The_Magic_Mountain\n',
    Pages: 720,
    Title: 'The Magic Mountain',
    Year: 1924,
    Price: 253,
  },
  {
    Id: '82c765d6-b865-417e-baa8-e264c3223753',
    Author: 'Herman Melville',
    Country: 'United States',
    ImageLink: 'assets/images/moby-dick.jpg',
    Language: 'English',
    Link: 'https://en.wikipedia.org/wiki/Moby-Dick\n',
    Pages: 378,
    Title: 'Moby Dick',
    Year: 1851,
    Price: 194,
  },
  {
    Id: 'e098726c-485a-42ad-939a-54f695903f25',
    Author: 'Michel de Montaigne',
    Country: 'France',
    ImageLink: 'assets/images/essais.jpg',
    Language: 'French',
    Link: 'https://en.wikipedia.org/wiki/Essays_(Montaigne)\n',
    Pages: 404,
    Title: 'Essays',
    Year: 1595,
    Price: 135,
  },
  {
    Id: '0a5284c4-139d-4403-92bd-811a244c3d40',
    Author: 'Elsa Morante',
    Country: 'Italy',
    ImageLink: 'assets/images/history.jpg',
    Language: 'Italian',
    Link: 'https://en.wikipedia.org/wiki/History_(novel)\n',
    Pages: 600,
    Title: 'History',
    Year: 1974,
    Price: 199,
  },
  {
    Id: 'a6f2242c-c73f-4ff3-8d0a-a32f47097298',
    Author: 'Toni Morrison',
    Country: 'United States',
    ImageLink: 'assets/images/beloved.jpg',
    Language: 'English',
    Link: 'https://en.wikipedia.org/wiki/Beloved_(novel)\n',
    Pages: 321,
    Title: 'Beloved',
    Year: 1987,
    Price: 130,
  },
  {
    Id: 'f4f1c76a-d543-4bc1-b978-f56493259779',
    Author: 'Murasaki Shikibu',
    Country: 'Japan',
    ImageLink: 'assets/images/the-tale-of-genji.jpg',
    Language: 'Japanese',
    Link: 'https://en.wikipedia.org/wiki/The_Tale_of_Genji\n',
    Pages: 1360,
    Title: 'The Tale of Genji',
    Year: 1006,
    Price: 155,
  },
  {
    Id: 'd97f2659-d9b4-43ef-8337-f4c793861b18',
    Author: 'Robert Musil',
    Country: 'Austria',
    ImageLink: 'assets/images/the-man-without-qualities.jpg',
    Language: 'German',
    Link: 'https://en.wikipedia.org/wiki/The_Man_Without_Qualities\n',
    Pages: 365,
    Title: 'The Man Without Qualities',
    Year: 1931,
    Price: 133,
  },
  {
    Id: 'c651d500-08ef-462e-87d9-0dd6ec96d2e2',
    Author: 'Vladimir Nabokov',
    Country: 'Russia/United States',
    ImageLink: 'assets/images/lolita.jpg',
    Language: 'English',
    Link: 'https://en.wikipedia.org/wiki/Lolita\n',
    Pages: 317,
    Title: 'Lolita',
    Year: 1955,
    Price: 278,
  },
  {
    Id: '1727ba08-22ff-4ffa-afcd-c0a1442d3e3d',
    Author: 'George Orwell',
    Country: 'United Kingdom',
    ImageLink: 'assets/images/nineteen-eighty-four.jpg',
    Language: 'English',
    Link: 'https://en.wikipedia.org/wiki/Nineteen_Eighty-Four\n',
    Pages: 272,
    Title: 'Nineteen Eighty-Four',
    Year: 1949,
    Price: 218,
  },
  {
    Id: '991dd632-6f20-4e08-8d41-b0dbda5bbad7',
    Author: 'Ovid',
    Country: 'Roman Empire',
    ImageLink: 'assets/images/the-metamorphoses-of-ovid.jpg',
    Language: 'Classical Latin',
    Link: 'https://en.wikipedia.org/wiki/Metamorphoses\n',
    Pages: 576,
    Title: 'Metamorphoses',
    Year: 100,
    Price: 278,
  },
  {
    Id: 'ecab861e-2097-4e45-8f87-7cb292dadb1e',
    Author: 'Fernando Pessoa',
    Country: 'Portugal',
    ImageLink: 'assets/images/the-book-of-disquiet.jpg',
    Language: 'Portuguese',
    Link: 'https://en.wikipedia.org/wiki/The_Book_of_Disquiet\n',
    Pages: 272,
    Title: 'The Book of Disquiet',
    Year: 1928,
    Price: 137,
  },
  {
    Id: 'bb400086-0e5b-4fb1-841c-25ae222fb5a2',
    Author: 'Edgar Allan Poe',
    Country: 'United States',
    ImageLink: 'assets/images/tales-and-poems-of-edgar-allan-poe.jpg',
    Language: 'English',
    Link: 'https://en.wikipedia.org/wiki/Edgar_Allan_Poe_bibliography#Tales\n',
    Pages: 842,
    Title: 'Tales',
    Year: 1950,
    Price: 286,
  },
  {
    Id: '2e1a9b8b-37b9-4999-86db-376ad3952a0c',
    Author: 'Marcel Proust',
    Country: 'France',
    ImageLink: 'assets/images/a-la-recherche-du-temps-perdu.jpg',
    Language: 'French',
    Link: 'https://en.wikipedia.org/wiki/In_Search_of_Lost_Time\n',
    Pages: 2408,
    Title: 'In Search of Lost Time',
    Year: 1920,
    Price: 128,
  },
  {
    Id: 'ce8b9a75-0b14-46a3-9bb7-b95bb18c20ba',
    Author: 'Fran\u00E7ois Rabelais',
    Country: 'France',
    ImageLink: 'assets/images/gargantua-and-pantagruel.jpg',
    Language: 'French',
    Link: 'https://en.wikipedia.org/wiki/Gargantua_and_Pantagruel\n',
    Pages: 623,
    Title: 'Gargantua and Pantagruel',
    Year: 1533,
    Price: 110,
  },
  {
    Id: 'a195ffd1-0e46-497f-a379-2cb286a8125b',
    Author: 'Juan Rulfo',
    Country: 'Mexico',
    ImageLink: 'assets/images/pedro-paramo.jpg',
    Language: 'Spanish',
    Link: 'https://en.wikipedia.org/wiki/Pedro_P%C3%A1ramo\n',
    Pages: 124,
    Title: 'Pedro P\u00E1ramo',
    Year: 1955,
    Price: 145,
  },
  {
    Id: 'cd034787-a112-4f3e-a45d-b3e0751ada6a',
    Author: 'Rumi',
    Country: 'Sultanate of Rum',
    ImageLink: 'assets/images/the-masnavi.jpg',
    Language: 'Persian',
    Link: 'https://en.wikipedia.org/wiki/Masnavi\n',
    Pages: 438,
    Title: 'The Masnavi',
    Year: 1236,
    Price: 137,
  },
  {
    Id: '96708b6e-d9ef-4253-baa8-5dba6e483d56',
    Author: 'Salman Rushdie',
    Country: 'United Kingdom, India',
    ImageLink: 'assets/images/midnights-children.jpg',
    Language: 'English',
    Link: 'https://en.wikipedia.org/wiki/Midnight%27s_Children\n',
    Pages: 536,
    Title: 'Midnight\u0027s Children',
    Year: 1981,
    Price: 147,
  },
  {
    Id: 'c9140ad2-6be7-46f7-abb9-e3da59ab4cbe',
    Author: 'Saadi',
    Country: 'Persia, Persian Empire',
    ImageLink: 'assets/images/bostan.jpg',
    Language: 'Persian',
    Link: 'https://en.wikipedia.org/wiki/Bustan_(book)\n',
    Pages: 298,
    Title: 'Bostan',
    Year: 1257,
    Price: 271,
  },
  {
    Id: 'f005c726-b96e-4209-a05c-14adb6727673',
    Author: 'Tayeb Salih',
    Country: 'Sudan',
    ImageLink: 'assets/images/season-of-migration-to-the-north.jpg',
    Language: 'Arabic',
    Link: 'https://en.wikipedia.org/wiki/Season_of_Migration_to_the_North\n',
    Pages: 139,
    Title: 'Season of Migration to the North',
    Year: 1966,
    Price: 172,
  },
  {
    Id: 'd8571c57-cf02-4d32-ade1-ed5f4dc2f98c',
    Author: 'Jos\u00E9 Saramago',
    Country: 'Portugal',
    ImageLink: 'assets/images/blindness.jpg',
    Language: 'Portuguese',
    Link: 'https://en.wikipedia.org/wiki/Blindness_(novel)\n',
    Pages: 352,
    Title: 'Blindness',
    Year: 1995,
    Price: 209,
  },
  {
    Id: '1367051e-50ba-4a7f-b738-b5bed374e68c',
    Author: 'William Shakespeare',
    Country: 'England',
    ImageLink: 'assets/images/hamlet.jpg',
    Language: 'English',
    Link: 'https://en.wikipedia.org/wiki/Hamlet\n',
    Pages: 432,
    Title: 'Hamlet',
    Year: 1603,
    Price: 121,
  },
  {
    Id: '1355a35d-d5c1-4ae9-8483-b46a89f3b667',
    Author: 'William Shakespeare',
    Country: 'England',
    ImageLink: 'assets/images/king-lear.jpg',
    Language: 'English',
    Link: 'https://en.wikipedia.org/wiki/King_Lear\n',
    Pages: 384,
    Title: 'King Lear',
    Year: 1608,
    Price: 186,
  },
  {
    Id: '2ad37f06-3fe3-40f4-9f7f-e20bfa13a8f1',
    Author: 'William Shakespeare',
    Country: 'England',
    ImageLink: 'assets/images/othello.jpg',
    Language: 'English',
    Link: 'https://en.wikipedia.org/wiki/Othello\n',
    Pages: 314,
    Title: 'Othello',
    Year: 1609,
    Price: 112,
  },
  {
    Id: '6cf509db-cd33-482c-aa65-92ec91eae8ac',
    Author: 'Sophocles',
    Country: 'Greece',
    ImageLink: 'assets/images/oedipus-the-king.jpg',
    Language: 'Greek',
    Link: 'https://en.wikipedia.org/wiki/Oedipus_the_King\n',
    Pages: 88,
    Title: 'Oedipus the King',
    Year: -430,
    Price: 254,
  },
  {
    Id: '8cd4df7a-ee1d-4c3e-880e-63e8bfbc85a6',
    Author: 'Stendhal',
    Country: 'France',
    ImageLink: 'assets/images/le-rouge-et-le-noir.jpg',
    Language: 'French',
    Link: 'https://en.wikipedia.org/wiki/The_Red_and_the_Black\n',
    Pages: 576,
    Title: 'The Red and the Black',
    Year: 1830,
    Price: 251,
  },
  {
    Id: 'f0e2f78f-135d-4fa7-8088-08cb4ebd893c',
    Author: 'Laurence Sterne',
    Country: 'England',
    ImageLink: 'assets/images/the-life-and-opinions-of-tristram-shandy.jpg',
    Language: 'English',
    Link: 'https://en.wikipedia.org/wiki/The_Life_and_Opinions_of_Tristram_Shandy,_Gentleman\n',
    Pages: 640,
    Title: 'The Life And Opinions of Tristram Shandy',
    Year: 1760,
    Price: 111,
  },
  {
    Id: '4749f7a7-e366-4db1-b8fe-4c3dd785292e',
    Author: 'Italo Svevo',
    Country: 'Italy',
    ImageLink: 'assets/images/confessions-of-zeno.jpg',
    Language: 'Italian',
    Link: 'https://en.wikipedia.org/wiki/Zeno%27s_Conscience\n',
    Pages: 412,
    Title: 'Confessions of Zeno',
    Year: 1923,
    Price: 181,
  },
  {
    Id: 'bc08c665-63d8-42f9-b2ba-cdc776bffb33',
    Author: 'Jonathan Swift',
    Country: 'Ireland',
    ImageLink: 'assets/images/gullivers-travels.jpg',
    Language: 'English',
    Link: 'https://en.wikipedia.org/wiki/Gulliver%27s_Travels\n',
    Pages: 178,
    Title: 'Gulliver\u0027s Travels',
    Year: 1726,
    Price: 187,
  },
  {
    Id: '4b34211d-8afa-453f-b7ed-fdbe8236c9ac',
    Author: 'Leo Tolstoy',
    Country: 'Russia',
    ImageLink: 'assets/images/war-and-peace.jpg',
    Language: 'Russian',
    Link: 'https://en.wikipedia.org/wiki/War_and_Peace\n',
    Pages: 1296,
    Title: 'War and Peace',
    Year: 1867,
    Price: 127,
  },
  {
    Id: 'a6f9790b-f815-45d0-8669-996b2ec99428',
    Author: 'Leo Tolstoy',
    Country: 'Russia',
    ImageLink: 'assets/images/anna-karenina.jpg',
    Language: 'Russian',
    Link: 'https://en.wikipedia.org/wiki/Anna_Karenina\n',
    Pages: 864,
    Title: 'Anna Karenina',
    Year: 1877,
    Price: 269,
  },
  {
    Id: '3810728f-cb78-4c79-8e55-9e8adf57ef6c',
    Author: 'Leo Tolstoy',
    Country: 'Russia',
    ImageLink: 'assets/images/the-death-of-ivan-ilyich.jpg',
    Language: 'Russian',
    Link: 'https://en.wikipedia.org/wiki/The_Death_of_Ivan_Ilyich\n',
    Pages: 92,
    Title: 'The Death of Ivan Ilyich',
    Year: 1886,
    Price: 142,
  },
  {
    Id: '6ee78edb-61c1-4bbb-8c03-53b24ca9b443',
    Author: 'Mark Twain',
    Country: 'United States',
    ImageLink: 'assets/images/the-adventures-of-huckleberry-finn.jpg',
    Language: 'English',
    Link: 'https://en.wikipedia.org/wiki/Adventures_of_Huckleberry_Finn\n',
    Pages: 224,
    Title: 'The Adventures of Huckleberry Finn',
    Year: 1884,
    Price: 109,
  },
  {
    Id: 'bbf62982-e1d1-42b7-9ba2-f5adc5ae2d7e',
    Author: 'Valmiki',
    Country: 'India',
    ImageLink: 'assets/images/ramayana.jpg',
    Language: 'Sanskrit',
    Link: 'https://en.wikipedia.org/wiki/Ramayana\n',
    Pages: 152,
    Title: 'Ramayana',
    Year: -450,
    Price: 231,
  },
  {
    Id: '5bb6bf18-c2b1-4dc5-a1af-cb12e9ed087a',
    Author: 'Virgil',
    Country: 'Roman Empire',
    ImageLink: 'assets/images/the-aeneid.jpg',
    Language: 'Classical Latin',
    Link: 'https://en.wikipedia.org/wiki/Aeneid\n',
    Pages: 442,
    Title: 'The Aeneid',
    Year: -23,
    Price: 124,
  },
  {
    Id: '4d296d00-2337-4fdf-ae8d-8549b0a25306',
    Author: 'Vyasa',
    Country: 'India',
    ImageLink: 'assets/images/the-mahab-harata.jpg',
    Language: 'Sanskrit',
    Link: 'https://en.wikipedia.org/wiki/Mahabharata\n',
    Pages: 276,
    Title: 'Mahabharata',
    Year: -700,
    Price: 211,
  },
  {
    Id: 'a501c0c1-b111-4e35-a475-0579261c2347',
    Author: 'Walt Whitman',
    Country: 'United States',
    ImageLink: 'assets/images/leaves-of-grass.jpg',
    Language: 'English',
    Link: 'https://en.wikipedia.org/wiki/Leaves_of_Grass\n',
    Pages: 152,
    Title: 'Leaves of Grass',
    Year: 1855,
    Price: 252,
  },
  {
    Id: '3b73e10b-b33c-4e28-a4cf-ae5f7a8fe050',
    Author: 'Virginia Woolf',
    Country: 'United Kingdom',
    ImageLink: 'assets/images/mrs-dalloway.jpg',
    Language: 'English',
    Link: 'https://en.wikipedia.org/wiki/Mrs_Dalloway\n',
    Pages: 216,
    Title: 'Mrs Dalloway',
    Year: 1925,
    Price: 115,
  },
  {
    Id: 'c759cbaf-fd45-4c96-a9be-2e346dc7386d',
    Author: 'Virginia Woolf',
    Country: 'United Kingdom',
    ImageLink: 'assets/images/to-the-lighthouse.jpg',
    Language: 'English',
    Link: 'https://en.wikipedia.org/wiki/To_the_Lighthouse\n',
    Pages: 209,
    Title: 'To the Lighthouse',
    Year: 1927,
    Price: 266,
  },
  {
    Id: 'e3f96213-aec2-42d2-9b3e-ee2fa3d6059e',
    Author: 'Marguerite Yourcenar',
    Country: 'France/Belgium',
    ImageLink: 'assets/images/memoirs-of-hadrian.jpg',
    Language: 'French',
    Link: 'https://en.wikipedia.org/wiki/Memoirs_of_Hadrian\n',
    Pages: 408,
    Title: 'Memoirs of Hadrian',
    Year: 1951,
    Price: 267,
  },
];
